batch_size: 4
num_workers: 4  # ajuste conforme sua GPU
iters: 8000

train_dataset:
  type: Dataset
  dataset_root: data/dimensionamento_foliar_full_notest
  train_path: data/dimensionamento_foliar_full_notest/train.txt
  num_classes: 3
  transforms:
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: data/dimensionamento_foliar_full_notest
  val_path: data/dimensionamento_foliar_full_notest/val.txt
  num_classes: 3
  transforms:
    - type: Normalize
  mode: val

test_dataset:
  type: Dataset
  dataset_root: data/dimensionamento_foliar_full_notest
  test_path: data/dimensionamento_foliar_full_notest/val.txt
  num_classes: 3
  transforms:
    - type: Normalize
  mode: test

optimizer:
  type: SGD
  momentum: 0.9
  weight_decay: 1.0e-4

lr_scheduler:
  type: PolynomialDecay
  #learning_rate: 0.004
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
  coef: [1]

# Configurações de checkpoint
checkpoint:
  save_dir: output/dimensionamento_foliar
  save_interval: 500
  keep_checkpoint_max: 5

# Configurações de logging
log_config:
  name: dimensionamento_foliar_training
  interval: 50

# Configurações de early stopping e validação
val_dataset_config:
  val_interval: 200
  early_stop:
    patience: 1500
    min_improvement: 0.001
