train_dataset:
  type: Dataset
  dataset_root: data/dimensionamento_foliar_full_oneclass
  train_path: data/dimensionamento_foliar_full_oneclass/train.txt
  num_classes: 2
  transforms:
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: data/dimensionamento_foliar_full_oneclass
  val_path: data/dimensionamento_foliar_full_oneclass/val.txt
  num_classes: 2
  transforms:
    - type: Normalize
  mode: val

test_dataset:
  type: Dataset
  dataset_root: data/dimensionamento_foliar_full_oneclass
  test_path: data/dimensionamento_foliar_full_oneclass/test.txt
  num_classes: 2
  transforms:
    - type: Normalize
  mode: test
