# Configurações base para o dataset LSIDBeans.
# Este arquivo define dataset, losses e parâmetros de treinamento básicos.
batch_size: 4
num_workers: 4  # ajuste conforme sua GPU
iters: 12000

train_dataset:
  type: LeafDataset
  dataset_root: data/lsidbeans
  train_path: data/lsidbeans/train.txt
  num_classes: 3
  transforms: #potencialmente ajustar 
    # - type: ResizeStepScaling
    #   min_scale_factor: 0.5
    #   max_scale_factor: 1.5
    #   scale_step_size: 0.25
    # - type: RandomPaddingCrop
    #   crop_size: [512, 512]
    - type: RandomHorizontalFlip
    - type: RandomDistort
      brightness_range: 0.25
      contrast_range: 0.25
      saturation_range: 0.25
    - type: Normalize
  mode: train

val_dataset:
  type: LeafDataset
  dataset_root: data/lsidbeans
  val_path: data/lsidbeans/val.txt
  num_classes: 3
  transforms:
    - type: Normalize
  mode: val

test_dataset:
  type: LeafDataset
  dataset_root: data/lsidbeans
  test_path: data/lsidbeans/test.txt
  num_classes: 3
  transforms:
    - type: Normalize
  mode: test

optimizer:
  type: SGD
  momentum: 0.9
  weight_decay: 1.0e-4

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.004
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: CrossEntropyLoss
      ignore_index: 255
      # seg_loss
    - type: MSELoss
      ignore_index: 255
      # area_loss
    
  coef: [1.0, 1.0]  # coeficiente para seg_loss e area_loss

# Configurações de checkpoint
checkpoint:
  save_dir: output/lsidbeans
  save_interval: 500
  keep_checkpoint_max: 5

# Configurações de logging
log_config:
  name: lsidbeans_training
  interval: 50

# Configurações de early stopping e validação
val_dataset_config:
  val_interval: 200
  early_stop:
    patience: 1500
    min_improvement: 0.001
