_base_: '../_base_/dimensionamento_foliar.yml'

batch_size: 9  # ajuste conforme sua GPU
num_workers: 6  # ajuste conforme sua CPU
iters: 8000 

early_stop:
  intervals: 7
  min_improvement: 0.001

precision: fp16
amp_level: O1

train_dataset:
  transforms:
  - type: ResizeStepScaling
    min_scale_factor: 0.5
    max_scale_factor: 2.0
    scale_step_size: 0.25
  - type: RandomPaddingCrop
    crop_size: [768, 768]
    category_max_ratio: 0.70
    ignore_index: 255
  - type: RandomHorizontalFlip
    prob: 0.5
  - type: RandomVerticalFlip
    prob: 0.1
  - type: RandomDistort
    brightness_range: 0.08
    contrast_range: 0.08
    saturation_range: 0.08
    brightness_prob: 0.5
    contrast_prob: 0.5
    saturation_prob: 0.5
  - type: RandomBlur
    prob: 0.12
  - type: RandomNoise
    prob: 0.08
  - type: Normalize

val_dataset:
  transforms:
  - type: Resize
    target_size: [768, 768]
  - type: Normalize

test_dataset:
  transforms:
  - type: Resize
    target_size: [768, 768]
  - type: Normalize

optimizer:
  _inherited_: False
  type: AdamW
  weight_decay: 0.001 
  custom_cfg:
  - name: pos_embed
    weight_decay_mult: 0.0
  - name: head
    lr_multi: 10.0
  - name: bn

lr_scheduler:
  type: PolynomialDecay
  #type: CosineAnnealingDecay
  learning_rate: 4.0e-4
  #T_max: 10000
  #eta_min: 1.0e-6
  warmup_iters: 1500
  warmup_start_lr: 1.0e-6

#loss:
#  types:
#    - type: LinearRampLoss
#      start_coefs: [0.8, 0.2]
#      end_coefs: [0.4, 0.6]
#      total_iters: 10000 # Ajuste conforme o tamanho do seu dataset/épocas
#  coef: [1] # O coeficiente aqui vira 1, pois a LinearRampLoss já faz a soma interna

loss:
  types:
    - type: MixedLoss
      losses:
        - type: OhemCrossEntropyLoss
          thresh: 0.85
          min_kept: 80000
          weight: [1.0, 2.5] # penaliza mais o fundo quando ele vira folha
        - type: LovaszSoftmaxLoss
      coef: [0.85, 0.15] # OHEM continua dominante, Lovasz só ajuda no contorno
  coef: [1.0]

model:
  type: PPMobileSegOnly
  num_classes: 2  # fundo + (folha + quadrado)
  backbone:
    type: MobileSeg_Base
    #inj_type: AAMSx8 //Desativando VIM
    out_feat_chs: [64, 128, 192] 
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/ade20k/pp_mobileseg/pretrain/model.pdparams
  
  # Pode ser true e congelar tudo ou ser um número N e congelar os N primeiros blocos do backbone.
  #freeze_backbone: 3
  upsample: interpolate

# Configurações de checkpoint e logging
checkpoint:
  save_dir: output/pp_mobileseg_dimensionamento_foliar
  save_interval: 250
  keep_checkpoint_max: 2

test_config:
  compute_area_rer: False
  eval_num_workers: 1

log_config:
  name: pp_mobileseg_dimensionamento_foliar
  interval: 50

