_base_: '../_base_/lsidbeans.yml'
# Configuração do modelo PPMobileSeg para o dataset LSIDBeans.
# As configurações específicas de otimização e agendamento de aprendizagem
# estão sobrepostas a partir do arquivo base. A perda contém duas entradas:
# - CrossEntropyLoss para segmentação
# - MSELoss para regressão de área por-pixel

batch_size: 16  # ajuste conforme sua GPU
num_workers: 6  # ajuste conforme sua CPU
iters: 26500 # por volta de 100 epochs

train_dataset:
  transforms:
  - type: RandomHorizontalFlip
  #  prob: 0.5
  - type: RandomVerticalFlip
  #  prob: 0.1
  #- type: RandomDistort
  #  brightness_range: 0.07
  #  contrast_range: 0.07
  #  saturation_range: 0.07
  #  brightness_prob: 0.4
  #  contrast_prob: 0.4
  #  saturation_prob: 0.4
  #- type: RandomBlur
  #  prob: 0.10
  #- type: RandomNoise
  #  prob: 0.06
  - type: Normalize

precision: fp16
amp_level: O1

optimizer:
  _inherited_: False
  type: AdamW
  #weight_decay: 0.001  # Reduzido para dataset pequeno
  custom_cfg:
  - name: pos_embed
    weight_decay_mult: 0.0
  - name: head
    lr_multi: 10.0
  - name: bn
    weight_decay_mult: 0.0

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.0004
  end_lr: 0
  power: 1.0
  warmup_iters: 2000
  warmup_start_lr: 1.0e-6

loss:
  types:
    - type: CrossEntropyLoss
    - type: L2Loss
      reduction: none # para aplicar máscara manualmente

  coef: [1.0, 3.0]  # [seg_coef, area_coef]

model:
  type: PPMobileSeg
  num_classes: 3  # fundo + folha + quadrado
  #freeze_backbone: 2
  backbone:
    type: MobileSeg_Base
    #inj_type: AAM
    out_feat_chs: [64, 128, 192] 
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/ade20k/pp_mobileseg/pretrain/model.pdparams
  upsample: intepolate

# Configurações de checkpoint e logging
checkpoint:
  save_dir: output/lsidbeans
  save_interval: 500
  keep_checkpoint_max: 4

log_config:
  name: pp_mobileseg_lsidbeans
  interval: 50

# Configurações de validação
val_dataset_config:
  val_interval: 500

test_config:
  compute_area_rer: True
  eval_num_workers: 1

#Early Stopping
early_stop:
  intervals: 8
  min_improvement: 0.5  # porcentagem mínima de melhora relativa no RER (ex.: 0.5 = 0.5%)